OSW_FILEDIR: "data/ID/osw_results/"
DIANN_FILEDIR: "data/PS/"
FDR_THRESHOLD: 0.01
TRIQLER_FC_EVAL: 0.51

MSCORE4PEPFDR_FFT: "1"
MSCORE4PEPFDR_FDR_TARGET: "0.01"

CONVERT_OSW_TO_MSTATS_N_TRANSITIONS: 6 
CONVERT_OSW_TO_MSTATS_MIN_PEPTIDES: 2
CONVERT_OSW_TO_MSTATS_MAX_PEPTIDES: 10
